version: "3.8"
services:
  wildfly:
    build:
      context: .
      args:
        dist: ubi9-minimal
        jdk: 21
        ssl_cert: ${COMMONS_LANGC_SSL_PATH}
        ssl_key: ${COMMONS_LANGC_SSL_KEY}
    image: lkhsoft/commons-langc-doc:v1
    ports:
      - "8443:8443"